### ISSUE TITLE
Multi-Image (of the Same Object)

### ISSUE THREAD

**Issue by MultiTrickFox** [VAST-AI-Research/TriplaneGaussian#7]
Is it possible to leverage multiple images of the same object?

**Comment by zouzx** [comment]
Of course, you can easily replace the single image tokens by gathering multi-view tokens for the model reconstruction.

**Comment by MultiTrickFox** [comment]
Could you guide me in the right direction please? assuming I have N images of an object from different angles, where/how should I start to modify the code?

**Comment by zouzx** [comment]
There should be two places that need modifications:
(1) input image tokens. Since the code of this part already supports multiple images (`Nv` means the number of input images), I think you only need to modify the dataset to load multiple images.
https://github.com/VAST-AI-Research/TriplaneGaussian/blob/e6a4939158bf91fa480c3dbcd295cc928059c607/infer.py#L114
(2) projection features. For this part, you need to modify the `points_projection` function in the following code to fuse multiple projection features from them, such as calculating the projection feature at each view and fusing them with average or other operations.  https://github.com/VAST-AI-Research/TriplaneGaussian/blob/e6a4939158bf91fa480c3dbcd295cc928059c607/infer.py#L123-L126

**Comment by MultiTrickFox** [comment]
Thank you!

**Comment by PatD123** [comment]
@MultiTrickFox Were you able to figure this out? Cuz I'm thinking of doing the same thing.
